---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: kong-validations
webhooks:
- name: validations.kong.konghq.com
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1beta1", "v1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
  - apiGroups:
    - ""
    apiVersions:
    - "v1"
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  clientConfig:
    service:
      namespace: kong
      name: kong-validation-webhook
    caBundle: <base64-encoded cert>
