language: go

notifications:
  email:
    on_failure: never
    on_success: never

cache:
  apt: true
  directories:
  - $GOPATH/pkg/mod

env:
- GO111MODULE=on

go:
  - "1.12"

go_import_path: github.com/kong/kubernetes-ingress-controller

before_script:
- go get golang.org/x/lint/golint
- diff -u <(echo -n) <(gofmt -d -s .)
- golint -set_exit_status .
- make verify-all
- make vet

script:
- make test
