apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Some resources may not have been processed by the base, so we have to replace
# both kong and kong-placeholder
images:
- name: kong
  newName: kong/kong-gateway
  newTag: '3.9' # renovate: datasource=docker versioning=docker depName=kong/kong-gateway@regenerate packageName=kong/kong-gateway
- name: kong-placeholder
  newName: kong/kong-gateway
  newTag: '3.9' # renovate: datasource=docker versioning=docker depName=kong/kong-gateway@regenerate packageName=kong/kong-gateway
