apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: kong-placeholder
  newName: kong
  newTag: '3.6'
- name: kic-placeholder
  newName: kong/kubernetes-ingress-controller
  newTag: '3.1'
